# Generated by Django 5.2.6 on 2026-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
