# Generated by Django 5.2.6 on 2026-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_group_postsmodel_group_groupmembership_group_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notif_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('FOLLOW', 'Follow'), ('MESSAGE', 'Message'), ('REQUEST', 'Message request')], default='LIKE', max_length=10),
        ),
    ]
